### PR TITLE
New icon layout for the icons on the desktop

### PR DESCRIPTION
**Pull request by william-os4y**
Please note that I've left the qDebug() in LDPlugin.h

### CODE REVIEW

**Comment by beanpole135** [comment]
Ok, my only concern with this is that the appearance of all the other desktop plugins will be broken because you only specified/fixed the stylesheet for the applauncher and desktopview plugins. Could you verify/fix the others as well first? I think the calander plugin will be fine, but the notepad and audioplayer plugins might look really strange.

**Comment by william-os4y** [comment]
I've just pushed a the theme for the other plugins

**Comment by beanpole135** [comment]
Looks good! Thanks for working on that!

**Comment by beanpole135** [comment]
I just made a couple quick adjustments to the new theme settings after running them on my system:
1) Use the specific widget for the custom settings (QToolButton, QListWidget) instead of a generic QWidget. This prevents some cascading changes to other aspects of the plugin (like the context menu for example). Remember that QWidget is the basis of almost every Qt element, so changes to it might touch a lot more than you expect... :-)
2) Adjust the font colors for the desktopview/applauncher plugins to use the disabled/highlighted font colors from the theme. This prevents issues (such as I experienced) where the base/accent colors are very similar and the text disappeared into the new background. By specifically using the "font" colors, it ensure that the text is visible on whatever base/accent color is used (that is the whole point of the special font colors in the scheme).
3) Remove a duplicate entry for the theme-based panel appearance.
4) Round off all the desktop plugin corners a bit more (5px border-radius)
5) Copy over the new settings to the "None" theme (since they only impact desktop appearance and not other windows/applications).

Overall, the new theme looks great! Thanks for working on that!

**Pull request merged**
