### PR TITLE
Preliminary NetBSD support

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by beanpole135** [comment]
Great!
Thanks for sending that in. If you like, you might be able to use some of the LuminaOS-FreeBSD support options/code when you start filling in the NetBSD support since NetBSD is based on an older FreeBSD version. I just don't know all the differences between them to tell you exactly which things to watch out for... :-)

**Comment by krytarowski** [comment]
Thank you for merging the code.

I don't know what do you mean by 'NetBSD is based on an older FreeBSD version'? NetBSD is even older..

**Comment by skarekrow** [comment]
I thought they were both derived from 386/BSD? They should be of equal age then.

**Comment by beanpole135** [comment]
Sorry - I got NetBSD and DragonFly confused for a bit there.
DragonFly was a derivative of FreeBSD 4.8 while NetBSD and FreeBSD were both derived from a common parent (386/BSD?).
In either case, my original sentiment is still valid - help yourself to the code from the other OS support layers (such as the FreeBSD support) if it will help you finish up the NetBSD support.  :-)

**Comment by beanpole135** [comment]
Ah, found a nice little chart/timeline on the NetBSD page showing the relationship between FreeBSD/NetBSD. Hope this helps clear up any confusion (in case someone else stumbles across this thread...).

https://www.netbsd.org/about/history.html

**Pull request merged**
