### PR TITLE
Fix type-o that caused tag mismatch in translation

### PR DESCRIPTION
**Pull request by beatgammit**

### CODE REVIEW

**Comment by beatgammit** [comment]
My build failed today and I'm pretty sure this is the reason why.

**Comment by beatgammit** [comment]
This now builds on Arch Linux with the [lumina-desktop-git](https://aur.archlinux.org/packages/lumina-desktop-git/) package.

**Comment by beanpole135** [comment]
Thanks for catching that!

**Comment by beatgammit** [comment]
No problem! Thanks for the merge!

**Pull request merged**
