### PR TITLE
LuminaOS-Debian #2

### PR DESCRIPTION
**Pull request by Nanolx**
Changes:
- LuminaOS-Debian: lumina-fm expects type:::filesystem::::path, we now ensure we always provide correct output  (some devices where not accessible)
- LuminaOS-Linux: lumina-fm expects type::::filesystem::::path, but instead we generated type::::read-write-flag::::path+"type"+filesystem, so most devices where not accessible, we now ensure to always provide correct output
- lumina-fm: when entry for / was generated the string became " type filesystem" instead, now the / is no longer deleted, but replaced by "root" (eg: "root type btrfs")
- lumina-fm: string changes for device labels (eg: "root (type: btrfs)")
- LuminaOS-Debian/LuminaOS-Linux: add device-type "LVM" (no different icon (yet) in lumina-fm)

### CODE REVIEW

**Comment by Nanolx** [comment]
Before merging, you should check the correctness of device labels in lumina-fm, either lumina-fm expects ::::file-system:::: to be the read-write-flag, and actual filesystem to be part of ::::path, or Linux' mount is different from BSD mount, thus the bogus output.

**Comment by beanpole135** [comment]
It looks good, I just noticed one possible error in the lumina-fm label detection (the absolute path could end with a "/" causing it to be labelled "root" when it is not), but that appears to be something that was still a possible bug in the old implementation as well, so I will go ahead and fix that really quick. 
BTW: What type of device is an "LVM"? A type of virtual machine I assume? I will go ahead an assign an icon for it, but I want to make sure that the icon makes sense for the type of device... :-)

**Comment by beanpole135** [comment]
Ok, I just cleaned up the device usage in lumina-fm. I also assigned the same icon for LVM as a harddrive, since that seems to be the most logical type of icon for both a virtual machine as well as a harddrive partition/manager (I did a quick search for LVM on google).

I also just double-checked the FreeBSD "mount" output/usage and it all looks good, so there must be differences from the Linux "mount" utility.

**Comment by Nanolx** [comment]
LVM stands for Logical Volume Manager. To put it plainly LVM allows for partitions to combined into one, even partitions across different physical devices. Thus you can have for example 4 physical partitions on 3 physical devices, combined into one logical partition (so if you run out of space, you add a new harddisk, combine it into the existing LVM and have new space on that partition). LVM alsow allows for encrypted partitions. The "mapper" comes from dm (device-mapper) that manages LVMs on Linux. I don't know if there's something like that on BSD.

**Pull request merged**
