### PR TITLE
Lumina Debian #5

### PR DESCRIPTION
**Pull request by Nanolx**
- new upstream snapshot
- add missing build dependency on libxcb-image0-dev
- add qt5-configuration-tool wrapper for Lumina-DE (use qt5ct QT_QPA_PLATFORMTHEME if /usr/bin/qt5ct exists and LUMINA_USE_QT5CT is TRUE in /etc/defaul/lumina-qt5ct)

For more info about qt5ct see http://qt-apps.org/content/show.php/Qt5+Configuration+Tool?content=168066 / Binary packages for Debian GNU/Linux (built by me): http://apt.nanolx.org/pool/main/q/qt5-configuration-tool/

Con: conflicts with lumina-config
Pro: It allows to use for example CDE, Windows, Motif, Plastique or GTK+2 theme for Qt5, generating a fonts.conf, using menu animations, custom QSS, etc., which is not possible (or not that detailed) with lumina-config alone.

By default qt5ct is not used, only if you set LUMINA_USE_QT5CT=TRUE in /etc/default/lumina-qt5ct. So this is safe (and only for Debian GNU/Linux as of now).

### CODE REVIEW

**Comment by Nanolx** [comment]
Second wave:

- drop lumina-core package
- add lumina-data package (contains arch-indep stuff like sounds, wallpapers, themes, so that they aren't shipped separately for each arch)
- make lumina-desktop what lumina-core has been before

**Comment by beanpole135** [comment]
Looks Good!
The only "conflict" with lumina-config would be in the Lumina theming department - but even that might still work fine (since the Lumina themes are stylesheet-based and should apply on top of any Qt theme engine).

Thanks for your work on this!

**Comment by Nanolx** [comment]
I just made a few more tests, and yes the Lumina themes do work 95% with qt5ct (there are minor glitches, but nothing one should worry about).

**Comment by beanpole135** [comment]
Good! Thanks for verifying that!

**Pull request merged**
